# Generated by Django 4.2.3 on 2023-07-31 22:43

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='background',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('descriptions', ckeditor.fields.RichTextField()),
                ('created_by', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '01. Background',
            },
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('categories', models.CharField(choices=[('home', 'home'), ('about', 'about'), ('team', 'team'), ('events', 'events'), ('donation', 'donation')], max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
            ],
            options={
                'verbose_name_plural': '07. Banners',
            },
        ),
        migrations.CreateModel(
            name='ChoozeUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('tag', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique_for_date='publish')),
                ('description', ckeditor.fields.RichTextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': '03. Why Choose us',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('describe_email', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '04. Emails',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('Company_name', models.CharField(max_length=200, unique=True)),
                ('P_o_box_no', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': '06. Location',
            },
        ),
        migrations.CreateModel(
            name='OfficePhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('Phone_number', models.CharField(max_length=13, unique=True)),
                ('describe_Phone_number', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '05. Office Phones',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique_for_date='publish')),
                ('design_view', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=225)),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='media/projcects')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('finshed', 'Finished'), ('pending', 'Pending')], default='published', max_length=10)),
                ('started', models.DateField()),
            ],
            options={
                'verbose_name_plural': '10. Projects',
            },
        ),
        migrations.CreateModel(
            name='ServeCaptin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, unique_for_date='publish')),
                ('caption', ckeditor.fields.RichTextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': '08. Services Caption',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, unique_for_date='publish')),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/Services')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': '09. Services',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=200, unique_for_date='publish')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('post', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='media/staff')),
                ('department', models.CharField(choices=[('survey', 'survey'), ('steel', 'Steel'), ('contruction', 'Contruction'), ('finishing', 'Finishing')], default='contruction', max_length=256)),
                ('join_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': '13. Team Members',
            },
        ),
        migrations.CreateModel(
            name='Who',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique_for_date='publish')),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='media/who')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('since', models.DateField()),
            ],
            options={
                'verbose_name_plural': '11. Who we are',
            },
        ),
    ]
