# Generated by Django 4.2.3 on 2023-08-01 16:18

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '12. Careers',
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('testify', ckeditor.fields.RichTextField()),
                ('role', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': '13. Testimonies',
            },
        ),
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': '06. Banners'},
        ),
        migrations.AlterModelOptions(
            name='choozeus',
            options={'verbose_name_plural': '02. Why Choose us'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name_plural': '03. Emails'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': '05. Location'},
        ),
        migrations.AlterModelOptions(
            name='officephone',
            options={'verbose_name_plural': '04. Office Phones'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': '09. Projects'},
        ),
        migrations.AlterModelOptions(
            name='servecaptin',
            options={'verbose_name_plural': '07. Services Caption'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': '08. Services'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': '11. Team Members'},
        ),
        migrations.AlterModelOptions(
            name='who',
            options={'verbose_name_plural': '10. Who we are'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='post',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
