# Generated by Django 4.2.3 on 2023-08-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0003_background_title_backgroudimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroudimages',
            options={'verbose_name_plural': '02. Back Images'},
        ),
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': '07. Banners'},
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name_plural': '14. Careers'},
        ),
        migrations.AlterModelOptions(
            name='choozeus',
            options={'verbose_name_plural': '03. Why Choose us'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name_plural': '04. Emails'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': '06. Location'},
        ),
        migrations.AlterModelOptions(
            name='officephone',
            options={'verbose_name_plural': '05. Office Phones'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': '10. Projects'},
        ),
        migrations.AlterModelOptions(
            name='servecaptin',
            options={'verbose_name_plural': '08. Services Caption'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': '09. Services'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': '12. Team Members'},
        ),
        migrations.AlterModelOptions(
            name='who',
            options={'verbose_name_plural': '11. Who we are'},
        ),
        migrations.AddField(
            model_name='staff',
            name='faceBook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
