# Generated by Django 4.2.3 on 2023-08-02 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0004_alter_backgroudimages_options_alter_banners_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroudimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='back'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='categories',
            field=models.CharField(choices=[('home', 'home')], max_length=200),
        ),
        migrations.AlterField(
            model_name='banners',
            name='image',
            field=models.ImageField(upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
