# Generated by Django 4.2.3 on 2023-08-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0005_alter_backgroudimages_image_alter_banners_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servecaptin',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='servecaptin',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='servecaptin',
            name='slug',
        ),
    ]
