# Generated by Django 4.2.3 on 2023-08-04 23:04

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0006_remove_servecaptin_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('body', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': '15. Mission',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': '17. main objective',
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('body', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': '16. Vision',
            },
        ),
    ]
