# Generated by Django 4.2.3 on 2023-08-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0007_mission_objective_vision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choozeus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='choozeus',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='choozeus',
            name='slug',
        ),
    ]
