# Generated by Django 4.2.3 on 2023-08-04 23:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0008_remove_choozeus_description_remove_choozeus_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choozeus',
            name='description',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
