# Generated by Django 4.2.3 on 2023-08-06 23:34

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0009_choozeus_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=256)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': '18. Read Messages',
            },
        ),
        migrations.AlterField(
            model_name='projects',
            name='started',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('finshed', 'Finished'), ('pending', 'Pending')], default='finshed', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('magement', 'Magement'), ('survey', 'survey'), ('steel', 'Steel'), ('contruction', 'Contruction'), ('finishing', 'Finishing')], default='contruction', max_length=256),
        ),
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='staff',
            name='post',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='staff',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
